runtime: nodejs18
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_memory_utilization: 0.65

env_variables:
  NODE_ENV: 'production'
entrypoint: npm start
handlers:
  - url: /.*
    script: auto